dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="powerdns-admin"
  #- image="monogramm/docker-powerdns-admin:travis-${VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}/"

script:
  #- travis_retry docker build -t "$image" "$dir"
  - cd "$dir"
  - travis_retry travis_wait 60 docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "$name" | grep "Up"
  - echo 'Wait until everything ready (2-3 minutes)' && sleep 180
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "$name" | grep "Up"

notifications:
  email: false

env: # Environments
    - VERSION=master VARIANT=alpine
    - VERSION=v0.1 VARIANT=alpine
