dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="powerdns-admin"
  #- image="monogramm/docker-powerdns-admin:travis-${VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}/"
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME=docker-powerdns-admin

script:
  #- travis_retry docker build -t "$image" "$dir"
  - cd "$dir"
  # Test containers build
  - docker-compose -f docker-compose.${DATABASE}.test.yml build
  - docker images
  # Test containers run
  - travis_retry docker-compose -f docker-compose.${DATABASE}.test.yml up -d && sleep 60
  - docker-compose -f docker-compose.${DATABASE}.test.yml ps
  - docker-compose -f docker-compose.${DATABASE}.test.yml logs
  - docker-compose -f docker-compose.${DATABASE}.test.yml ps "$name" | grep "Up"
  - echo 'Wait until everything ready (2-3 minutes)' && sleep 180
  - docker-compose -f docker-compose.${DATABASE}.test.yml ps
  - docker-compose -f docker-compose.${DATABASE}.test.yml logs
  - docker-compose -f docker-compose.${DATABASE}.test.yml ps "$name" | grep "Up"
  # Test containers can be dropped and restarted
  - docker-compose -f docker-compose.${DATABASE}.test.yml down
  - travis_retry docker-compose -f docker-compose.${DATABASE}.test.yml up -d && sleep 60
  - echo 'Wait until everything ready (2-3 minutes)' && sleep 180
  - docker-compose -f docker-compose.${DATABASE}.test.yml ps
  - docker-compose -f docker-compose.${DATABASE}.test.yml logs
  - docker-compose -f docker-compose.${DATABASE}.test.yml ps "$name" | grep "Up"

notifications:
  email: false

matrix:
  allow_failures:
    - env: VERSION=v0.1 VARIANT=alpine DATABASE=mysql
    - env: VERSION=v0.1 VARIANT=alpine DATABASE=postgres
    - env: VERSION=v0.1 VARIANT=alpine DATABASE=sqlite

env: # Environments
    - VERSION=master VARIANT=alpine DATABASE=sqlite
    - VERSION=master VARIANT=alpine DATABASE=postgres
    - VERSION=master VARIANT=alpine DATABASE=mysql
    - VERSION=v0.1 VARIANT=alpine DATABASE=sqlite
    - VERSION=v0.1 VARIANT=alpine DATABASE=postgres
    - VERSION=v0.1 VARIANT=alpine DATABASE=mysql
    - VERSION=v0.2 VARIANT=alpine DATABASE=sqlite
    - VERSION=v0.2 VARIANT=alpine DATABASE=postgres
    - VERSION=v0.2 VARIANT=alpine DATABASE=mysql
