os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_script:
  - env | sort
  - name="powerdns-admin"
  #- image="monogramm/docker-powerdns-admin:travis-${VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}/"
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME=docker-powerdns-admin

script:
  - cd "$dir"
  # Test containers build
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml build
  - docker images
  # Test containers run
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml up -d && sleep 60
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml ps
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml logs "$name"
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml ps "$name" | grep "Up"
  - echo 'Wait until everything ready (2-3 minutes)' && sleep 180
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml ps
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml logs "$name"
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml ps "$name" | grep "Up"
  # Test containers can be dropped and restarted
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml down
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml up -d && sleep 60
  - echo 'Wait until everything ready (2-3 minutes)' && sleep 180
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml ps
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml logs "$name"
  - docker-compose -f docker-compose.${DATABASE}${DC_SUFFIX}.yml ps "$name" | grep "Up"

notifications:
  email: false

matrix:
  allow_failures:
    - env: VERSION=v0.1 VARIANT=alpine DATABASE=mysql DC_SUFFIX=.test
    - env: VERSION=v0.1 VARIANT=alpine DATABASE=postgres DC_SUFFIX=.test
    - env: VERSION=v0.1 VARIANT=alpine DATABASE=sqlite DC_SUFFIX=
    - env: VERSION=v0.2 VARIANT=alpine DATABASE=sqlite DC_SUFFIX=
    - env: VERSION=master VARIANT=alpine DATABASE=sqlite DC_SUFFIX=

env: # Environments
    - VERSION=master VARIANT=alpine DATABASE=sqlite DC_SUFFIX=
    - VERSION=master VARIANT=alpine DATABASE=postgres DC_SUFFIX=.test
    - VERSION=master VARIANT=alpine DATABASE=mysql DC_SUFFIX=.test
    - VERSION=v0.1 VARIANT=alpine DATABASE=sqlite DC_SUFFIX=
    - VERSION=v0.1 VARIANT=alpine DATABASE=postgres DC_SUFFIX=.test
    - VERSION=v0.1 VARIANT=alpine DATABASE=mysql DC_SUFFIX=.test
    - VERSION=v0.2 VARIANT=alpine DATABASE=sqlite DC_SUFFIX=
    - VERSION=v0.2 VARIANT=alpine DATABASE=postgres DC_SUFFIX=.test
    - VERSION=v0.2 VARIANT=alpine DATABASE=mysql DC_SUFFIX=.test
