version: "2.3"

networks:
  default:

volumes:
  powerdns-admin-upload:
  powerdns-admin-logs:
  powerdns-admin-db:
  # SQLite
  powerdns-sqlite-data:

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - powerdns-admin
      - pdns-server
    volumes_from:
      - powerdns-admin
    environment:
      - DOCKER_TEST_CONTAINER=powerdns-admin
      - DOCKER_WEB_CONTAINER=powerdns-admin
      - DOCKER_WEB_PORT=${PDA_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  powerdns-admin:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - TAG=${DOCKER_TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    image: ${IMAGE_NAME}
    hostname: powerdns-admin
    container_name: powerdns-admin
    mem_limit: 256M
    memswap_limit: 256M
    healthcheck:
      test: ["CMD", "wget","--output-document=-","--quiet","--tries=1","http://127.0.0.1:9191/"]
    depends_on:
      - pdns-server
    ports:
      - "9191:${PDA_PORT}"
    volumes:
      - powerdns-admin-upload:/var/www/powerdns-admin/upload
      - powerdns-admin-logs:/var/www/powerdns-admin/logs
      - powerdns-admin-db:/var/www/powerdns-admin/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    environment:
      # Database configuration
      - PDA_DB_NAME=${PDA_DB_NAME}
      - PDA_DB_USER=${PDA_DB_USER}
      - PDA_DB_PASSWORD=${PDA_DB_PASSWORD}
      # SQLite
      - PDA_DB_TYPE=sqlite
      # Gunicorn configuration
      - BIND_ADDRESS=0.0.0.0
      - PORT=${PDA_PORT}
      # Admin user
      - ADMIN_USERNAME=${PDA_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${PDA_ADMIN_PASSWORD}
      - ADMIN_FIRSTNAME=${PDA_ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${PDA_ADMIN_LASTNAME}
      - ADMIN_EMAIL=${PDA_ADMIN_EMAIL}
      # PowerDNS-Admin configuration
      - PDNS_PROTO=${PDNS_PROTO}
      - PDNS_HOST=pdns-server
      - PDNS_PORT=${PDNS_PORT}
      - PDNS_API_URL=${PDNS_PROTO}://pdns-server:${PDNS_PORT}/api/v1
      - PDNS_API_KEY=${PDNS_API_KEY}
      - SIGNUP_ENABLED=False

  pdns-server:
    image: monogramm/docker-powerdns:develop
    hostname: pdns-server
    container_name: pdns-server
    restart: always
    ports:
      - "5053:53"
      - "5053:53/udp"
    networks:
      - default
    volumes:
      - powerdns-sqlite-data:/srv/pdns/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - AUTOCONF=sqlite
      # SQLite
      - SQLITE_DB=/srv/pdns/db/${PDNS_DB_NAME}
      - SQLITE_DNSSEC=no
      # PDNS Config
      - PDNS_API=yes
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_WEBSERVER_ADDRESS=0.0.0.0
      - PDNS_WEBSERVER_PORT=${PDNS_PORT}
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM}/0
      - PDNS_SOA_REFRESH_DEFAULT=14400
