version: "2.1"

services:
  powerdns-admin:
    build: .
    image: powerdns-admin
    hostname: powerdns-admin
    container_name: powerdns-admin
    mem_limit: 256M
    memswap_limit: 256M
    ports:
      - "9191:${PDA_PORT}"
    volumes:
      - powerdns-admin-upload:/var/www/powerdns-admin/upload
      - powerdns-admin-logs:/var/www/powerdns-admin/logs
      - powerdns-admin-db:/var/www/powerdns-admin/db
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    environment:
      # Database configuration
      - PDA_DB_NAME=${PDA_DB_NAME}
      - PDA_DB_USER=${PDA_DB_USER}
      - PDA_DB_PASSWORD=${PDA_DB_PASSWORD}
      # PostgreSQL
      - PDA_DB_TYPE=postgresql
      - PDA_DB_HOST=${PDA_DB_HOST}
      - PDA_DB_PORT=5432
      # Gunicorn configuration
      - BIND_ADDRESS=0.0.0.0
      - PORT=${PDA_PORT}
      # Admin user
      - ADMIN_USERNAME=${PDA_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${PDA_ADMIN_PASSWORD}
      - ADMIN_FIRSTNAME=${PDA_ADMIN_FIRSTNAME}
      - ADMIN_LASTNAME=${PDA_ADMIN_LASTNAME}
      - ADMIN_EMAIL=${PDA_ADMIN_EMAIL}
      # PowerDNS-Admin configuration
      - PDNS_API_URL=http://${PDNS_HOST}:8081/api/v1
      - PDNS_API_KEY=${PDNS_API_KEY}
      - SIGNUP_ENABLED=False
    # PostgreSQL
    depends_on: powerdns-admin-postgresql

  # PostgreSQL
  powerdns-admin-postgresql:
    image: postgres:10-alpine
    hostname: ${PDA_DB_HOST}
    container_name: ${PDA_DB_HOST}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - powerdns-admin-postgresql-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_DB=${PDA_DB_NAME}
      - POSTGRES_USER=${PDA_DB_USER}
      - POSTGRES_PASSWORD=${PDA_DB_PASSWORD}

  pdns-server:
    image: monogramm/docker-powerdns:develop
    hostname: ${PDNS_HOST}
    container_name: ${PDNS_HOST}
    ports:
      - "5053:53"
      - "5053:53/udp"
    networks:
      - default
    environment:
      - AUTOCONF=postgres
      # PostgreSQL
      - PGSQL_HOST=${PDNS_DB_HOST}
      - PGSQL_PORT=5432
      - PGSQL_DB=${PDA_DB_NAME}
      - PGSQL_USER=${PDNS_DB_USER}
      - PGSQL_PASS=${PDNS_DB_PASSWORD}
      - PGSQL_DNSSEC=no
      - PDNS_API=yes
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_WEBSERVER_ADDRESS=0.0.0.0
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM}/0
      - PDNS_SOA_REFRESH_DEFAULT=14400
    depends_on: ${PDNS_DB_HOST}

  pdns-postgresql:
    image: postgres:10-alpine
    hostname: ${PDNS_DB_HOST}
    container_name: ${PDNS_DB_HOST}
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${PDNS_DB_NAME}
      - POSTGRES_USER=${PDNS_DB_USER}
      - POSTGRES_PASSWORD=${PDNS_DB_PASSWORD}
    volumes:
      -  powerdns-postgresql-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  default:

volumes:
  powerdns-admin-upload:
  powerdns-admin-logs:
  powerdns-admin-db:
  # PostgreSQL
  powerdns-admin-postgresql-data:
  powerdns-postgresql-data:
