
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['v0.2']
        variant: ['alpine']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI hooks
        id: docker_hooks
        run: |
          cd images/${{ matrix.version }}
          ./hooks/run

      - name: Display docker images
        run: docker images
